### ISSUE TITLE
arm64 images?

### ISSUE THREAD

**Issue by IngwiePhoenix** [solidtime-io/self-hosting-examples#2]
Hello there!

Really quick question: Will there be ARM64 images?

This is just a PHP app - so it seems fairly trivial to build arm images?

Kind regards,
Ingwie

**Comment by korridor** [comment]
Thanks for the suggestion. We tried that a few weeks ago, and it made the GitHub action extremely slow. I'll make me a task and look into this again if we can do this differently to speed up the build process.
