### ISSUE TITLE
White page using the provided exemple

### ISSUE THREAD

**Issue by lejacobroy** [solidtime-io/self-hosting-examples#3]
I'm trying to start the [Docker + Database](https://github.com/solidtime-io/self-hosting-examples/tree/main/1-docker-with-database) exemple, but i'm getting a whitepage as it redirect to "domain/login". My domain is an internal tailscale IP address, so i'm not using a reverse proxy at this time.

The /health-check/debug endpoint gives me this result : `{"ip_address":"100.71.3.39","hostname":"100.89.105.23","timestamp":1728140584,"date_time_utc":"2024-10-05 15:03:04","date_time_app":"2024-10-05 15:03:04","timezone":"Etc\/UTC","secure":false,"is_trusted_proxy":true}`

When looking at the browser console, I can see this error : `Failed to load resource: An SSL error has occurred and a secure connection to the server cannot be made.` However, if I try to disable https and disable "APP_FORCE_HTTPS" in laravel.env, I get the same error.

**Comment by korridor** [comment]
@lejacobroy 

1. Could you provide me with the URL the browser tries to send a request to, that produces this error? You can see that in the Network tab.
2. What did you put in the `APP_URL` env variable in the `laravel.env` file?

**Comment by BoxOfSnoo** [comment]
I was getting the same thing, same health-check response and console error (also some CORS errors).

I put my domain in the .env file, ensured that Traefik had green checkmarks on each http and https connections and it eventually worked.  If you're using it on an IP address, try putting that address in the APP_DOMAIN setting in the .env file.

**Comment by korridor** [comment]
We released a fix for self-hosting setups without a HTTPS reverse proxy in this release: https://github.com/solidtime-io/solidtime/releases/tag/v0.3.1

Please try if this fixes your problem. If it doesn't please reopen the issue.
