### ISSUE TITLE
 403 Invalid signature in verify email address process

### ISSUE THREAD

**Issue by figachek** [solidtime-io/self-hosting-examples#5]
Hello,
i have error "403 Invalid signature" after click on activation link in email.
I previously generated keys 
```
docker compose run scheduler php artisan self-host:generate-keys
``` 
and added them to laravel.env
Please help

**Comment by figachek** [comment]
ip_address	"79.101.144.111"
hostname	"tt.yurkov.tech"
timestamp	1729059805
date_time_utc	"2024-10-16 06:23:25"
date_time_app	"2024-10-16 06:23:25"
timezone	"Etc/UTC"
secure	false
is_trusted_proxy	true

laravel.env
```
APP_NAME="solidtime"
VITE_APP_NAME="solidtime"
APP_ENV="production"
APP_DEBUG="false"
APP_URL="https://tt.yurkov.tech"
APP_FORCE_HTTPS="true"
TRUSTED_PROXIES="0.0.0.0/0,2000:0:0:0:0:0:0:0/3"

SUPER_ADMINS="figachek@me.com"

# Logging
LOG_CHANNEL="stderr_daily"
LOG_LEVEL="debug"

# Database
DB_CONNECTION="pgsql"
DB_HOST="postgres"
DB_PORT="5432"
DB_SSLMODE="require"
DB_DATABASE="solidtime_db"
DB_USERNAME="postgres_user"
DB_PASSWORD="j4tRkjF8FdndvWy6SB652zdS0p"

# Mail
MAIL_MAILER="smtp"
MAIL_HOST="smtp.mail.me.com"
MAIL_PORT="587"
MAIL_ENCRYPTION="tls"
MAIL_FROM_ADDRESS="figachek@me.com"
MAIL_FROM_NAME="solidtime"
MAIL_USERNAME="figachek@me.com"
MAIL_PASSWORD="bxqg-wfgc-efox-pjqx"

# Queue
QUEUE_CONNECTION="database"

# File storage
FILESYSTEM_DISK="local"
PUBLIC_FILESYSTEM_DISK="public"

APP_KEY="base64:A"
PASSPORT_PRIVATE_KEY="-----BEGIN PRIVATE KEY-----"
PASSPORT_PUBLIC_KEY="-----BEGIN PUBLIC KEY-----"

```

**Comment by korridor** [comment]
We released this fix in this release: https://github.com/solidtime-io/solidtime/releases/tag/v0.3.1

If this does not fix your problem, please reopen the issue.

**Comment by gioman** [comment]
> We released this fix in this release: https://github.com/solidtime-io/solidtime/releases/tag/v0.3.1
> 
> If this does not fix your problem, please reopen the issue.


@korridor I have just deployed solidtime (using the docker + database example) and I'm getting the same problem. Everything else seems to work. I'm using nginx proxy manager as reverse proxy and I'm letting NPM to take care of forcing SSL and of certificates.






> Can you check if the request that hits the solidtime container has a `X-Forwarded-Proto` header and if the value is `https`?

I would say no

```
GET /team-invitations/1caf1156... HTTP/2
Host: my.domain.pt
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:143.0) Gecko/20100101 Firefox/143.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br, zstd
DNT: 1
Connection: keep-alive
Cookie: XSRF-TOKEN=eyJpdiI6IlB1L3...
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
TE: trailers
Priority: u=0, i
Pragma: no-cache
Cache-Control: no-cache
```


Happy to give you more details if it helps troubleshoot.

**Comment by gioman** [comment]
> and I'm letting NPM to take care of forcing SSL and of certificates

for this in laravel.env I have

```
APP_URL="http://my.domain.pt/"
APP_FORCE_HTTPS="false"
```

but not sure if this is correct (anyway using there "https" and/or "true" does not seem to change anything).

**Comment by gioman** [comment]
If in NPM I don't force SSL and use http instead of https in the invitation link, then it works.
