### ISSUE TITLE
cant run

### ISSUE THREAD

**Issue by mikestaub** [solidtime-io/self-hosting-examples#6]
using the traefik version on docker for mac:

docker compose up -d
network reverse-proxy-docker-traefik_routing declared as external, but could not be found

**Comment by Uter1007** [comment]
[2024-11-08 17:11:16] production.ERROR: SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation "jobs" does not exist
queue-1      | LINE 1: select * from "jobs" where "queue" = $1 and (("reserved_at" ...
queue-1      |                       ^ (Connection: pgsql, SQL: select * from "jobs" where "queue" = default and (("reserved_at" is null and "available_at" <= 1731085876) or ("reserved_at" <= 1731085786)) order by "id" asc limit 1 FOR UPDATE SKIP LOCKED) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42P01): SQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \"jobs\" does not exist

**Comment by taliba570** [comment]
what a waste of time, it doesn't work
1-docker-with-database-scheduler-run-daedac9b2566

keep stopping database-scheduler and doesn't gives any error, initially it was not setting the app_key in the env I somehow fixed it but still doesn't works

**Comment by korridor** [comment]
@mikestaub I assume you used the example [0-docker-traefik-with-database](https://github.com/solidtime-io/self-hosting-examples/tree/main/0-docker-traefik-with-database#example-docker--traefik--database). If you read the README under "Prerequisites" it clearly states that you need a Traefik set up for this to work, this is why you get the error. The network is the external network name of the Traefik that is configurable. If you use [the repository linked in the README](https://github.com/korridor/reverse-proxy-docker-traefik) the name of the external network would be `reverse-proxy-docker-traefik_routing`. If you need more information about the setup please read [our very detailed documentation](https://docs.solidtime.io/self-hosting/intro).

**Comment by korridor** [comment]
@taliba570 If you think the release is broken, which I highly doubt is your issue, please provide at least some information for us to be able to reproduce your issue.

Until then I can only advice you to [read our documentation](https://docs.solidtime.io/self-hosting/guides/docker).

**Comment by Nkaati** [comment]
> [@mikestaub](https://github.com/mikestaub) I assume you used the example [0-docker-traefik-with-database](https://github.com/solidtime-io/self-hosting-examples/tree/main/0-docker-traefik-with-database#example-docker--traefik--database). If you read the README under "Prerequisites" it clearly states that you need Traefik set up for this to work, this is why you get the error. The network is the external network name of the Traefik that is configurable. If you use [the repository linked in the README](https://github.com/korridor/reverse-proxy-docker-traefik) the name of the external network would be `reverse-proxy-docker-traefik_routing`. If you need more information about the setup please read [our very detailed documentation](https://docs.solidtime.io/self-hosting/intro).

I was trying to get Traefik running locally but the docker-compose.yml doesn't run following the instructions.
ERR Error while creating certificate store error="failed to load X509 key pair: tls: failed to find any PEM data in certificate input" tlsStoreName=default

It's also not very clear for me if the "Connect docker compose service to reverse-proxy" section of the instructions is another yaml file that I'm suppose to create?  Either way I can't get a dash board up and running.  Maybe I need to pick different ports then 80 and 443?
Thanks.
